### ISSUE TITLE
我运行了你的项目，结果这样了，我初学node

### ISSUE THREAD

**Issue by caichunyu** [Fee-ing/Fee-movie#1]
Error
Looks like something broke!

        
Error: getaddrinfo ENOTFOUND www.80s.ai www.80s.ai:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)

**Comment by Fee-ing** [comment]
抱歉，现在才看到。因为这个网址已经失效了，所以爬取资源失败了。目前已将这个网址注释了。
